name: Calcular Edad Para Personas
 
on:

  push:
    inputs:
      dia:
        description: 'DIA NACIMIENTO'
        required: true
        default: '1'
      mes:
        description: 'MES NACIMIENTO'
        required: true
        default: '1'
      ano:
        description: 'AÑO NACIMIENTO'
        required: true
        default: '2021'
env:
  LIM_NINEZ: 13
  LIM_ADOLESCENCIA: 17
  LIM_ADULTO_JOVEN: 35
  LIM_ADULTO: 64 

jobs:

  edad:

    name: Calcular la edad

    runs-on: ubuntu-latest

    outputs:
      pasarEdad: ${{ steps.calculo.outputs.pasarEdad }}

    steps:

      - name: Calcular edad escrita
        id: calculo
        run: |
          dia=${{ github.event.inputs.dia }}
          mes=${{ github.event.inputs.mes }}
          ano=${{ github.event.inputs.ano }}

          hoy=$(date +%Y-%m-%d) 
          nacimiento="$ano-$mes-$dia"

          ano_actual=$(date +%Y)
          mes_actual=$(date +%m)
          dia_actual=$(date +%d)

          edad1=$((ano_actual - ano))

          if [[ "$mes_actual" -lt "$mes" ]] || { [[ "$mes_actual" -eq "$mes" ]] && [[ "$dia_actual" -lt "$dia" ]]; }; then
          edad1=$((edad1 - 1))
          fi

          echo "Tienes $edad1 anos."
          echo "pasarEdad=$edad1" >> $GITHUB_OUTPUT

  etapa:

    name: Verificar etapa

    runs-on: ubuntu-latest

    needs: edad 

    outputs:
      clasificacion: ${{ steps.etapa_id.outputs.clasificacion }}

    steps:

      - name: etapa obtenida
        id: etapa_id
        run: |
          edadviejo=${{ needs.edad.outputs.pasarEdad }}

          if [ "$edadviejo" -ge 5 ] && [ "$edadviejo" -le "$LIM_NINEZ" ]; then
            etapa='esta en etapa de ninez'
          elif [ "$edadviejo" -ge 14 ] && [ "$edadviejo" -le "$LIM_ADOLESCENCIA" ]; then
            etapa='esta en etapa de adolescencia'
          elif [ "$edadviejo" -ge 18 ] && [ "$edadviejo" -le "$LIM_ADULTO_JOVEN" ]; then
            etapa='esta en etapa de adulto joven'
          elif [ "$edadviejo" -ge 36 ] && [ "$edadviejo" -le "$LIM_ADULTO" ]; then
            etapa='esta en etapa de adulto'
          elif [ "$edadviejo" -ge 65 ]; then
            etapa='esta en etapa de tercera edad'
          else
            etapa='etapa fuera de rango'
          fi

          echo "clasificacion=$etapa" >> $GITHUB_OUTPUT
          echo "Etapa: $etapa"

 
