name: Wikipedia OnThisDay

on:
  workflow_dispatch:

jobs:
  fetch-wikimedia:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener datos de Wikimedia OnThisDay
        run: |
          LANGUAGE="es"
          MONTH=$(date +%m)
          DAY=$(date +%d)

          echo "Consultando: $LANGUAGE $MONTH $DAY"

          curl --request GET \
            --url "https://api.wikimedia.org/feed/v1/wikipedia/${LANGUAGE}/onthisday/selected/${MONTH}/${DAY}" \
            --header "accept: application/json" \
            --header "User-Agent: GitHubActionBot/1.0 (yourname@example.com)"


