name: Wikipedia OnThisDay

on:
  workflow_dispatch:

jobs:
  fetch-wikimedia:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener datos y contar noticias destacadas
        run: |
          set -x  # Habilita modo depuración para ver errores línea por línea

          LANGUAGE="es"
          MONTH=$(date +%m)
          DAY=$(date +%d)

          echo "Consultando: $LANGUAGE $MONTH $DAY"

          RESPONSE=$(curl --silent --request GET \
            --url "https://api.wikimedia.org/feed/v1/wikipedia/${LANGUAGE}/onthisday/selected/${MONTH}/${DAY}" \
            --header "accept: application/json" \
            --header "User-Agent: GitHubActionBot/1.0 (you@example.com)")

          echo "Respuesta recibida:"
          echo "$RESPONSE"

          # Validar que la respuesta no esté vacía
          if [ -z "$RESPONSE" ]; then
            echo "ERROR: La respuesta está vacía. Falló la consulta."
            exit 1
          fi

          COUNT=$(echo "$RESPONSE" | jq '.selected | length')

          echo "Número de eventos destacados en esta fecha: $COUNT"




