name: Consulta_Wikipedia

on:
  workflow_dispatch:
    inputs:
      MM:
        description: 'Mes (MM)'
        required: true
        default: '01'
      DD:
        description: 'Día (DD)'
        required: true
        default: '01'

jobs:
  fetch-wikimedia:
    runs-on: ubuntu-latest
    env:
      LANG: ${{ vars.LANG }}

    steps:
      - name: Configurar variables de fecha y cache
        id: vars
        run: |
          echo "LANGUAGE=$LANG" >> $GITHUB_ENV
          echo "MONTH=${{ github.event.inputs.MM }}" >> $GITHUB_ENV
          echo "DAY=${{ github.event.inputs.DD }}" >> $GITHUB_ENV
          echo "FILENAME=wikimedia_${LANG}_${{ github.event.inputs.MM }}-${{ github.event.inputs.DD }}.json" >> $GITHUB_ENV
          echo "CACHE_KEY=wikimedia_cache_${LANG}_${{ github.event.inputs.MM }}-${{ github.event.inputs.DD }}" >> $GITHUB_ENV

      - name: Restaurar cache si existe
        uses: actions/cache@v4
        with:
          path: ${{ env.FILENAME }}
          key: ${{ env.CACHE_KEY }}

      - name: Consultar API solo si no hay cache
        run: |
          if [ -f "${FILENAME}" ]; then
            echo "Cache encontrado: ${FILENAME}"
          else
            echo "Cache no encontrado. Consultando API..."
            RESPONSE=$(curl --silent --request GET \
              --url "https://api.wikimedia.org/feed/v1/wikipedia/${LANGUAGE}/onthisday/selected/${MONTH}/${DAY}" \
              --header "accept: application/json" \
              --header "User-Agent: GitHubActionBot/1.0 (email@pruebas.com)")

            if [ -z "$RESPONSE" ]; then
              echo "ERROR: La respuesta está vacía. Falló la consulta."
              exit 1
            fi

            echo "$RESPONSE" > "${FILENAME}"
            echo "Respuesta guardada en archivo: ${FILENAME}"
          fi

      - name: Leer y procesar el archivo cacheado o generado
        run: |
          RESPONSE=$(cat "${FILENAME}")

          COUNT=$(echo "$RESPONSE" | jq '.selected | length')
          echo "Número de eventos destacados: $COUNT"

          echo "Eventos destacados:"
          echo "$RESPONSE" | jq -r '.selected[] | "\(.text)\nTítulo: \(.pages[0].title)\nURL: \(.pages[0].content_urls.desktop.page)\n"'
